In [3]:
import numpy as np
import pandas as pd
from typing import List
import struct
from array import array

# reading the sizes file, unpacking byte by byte as uint8 by using struct

In [4]:
#verifying the atomids by using the helper function from part 1
def get_el_sym(atom_ids:np.ndarray) -> List[str]:
    """Helper method which turns atom_ids into element symbols."""
    elmap = "H B C N O F Na Si P S Cl K Se Br I X".split(" ")
    return [elmap[id] for id in atom_ids]

In [5]:
def get_coordinate_for_molecule(mol_index, size, coordinates):
        
    if mol_index ==1:
        return coordinates[:size[1]]
    else:
        starting_element = 0
        ending_ele = 0
        for i in range(mol_index):
            starting_element +=size[i]

        ending_ele = size[mol_index]+starting_element

        return coordinates[starting_element:ending_ele]

In [6]:
def read_files(working_dir, mol_index):
    file_name = fif(mol_index)
    
    with open(working_dir +f"moldata-{file_name}-sizes.dat", "rb") as size_file:
        size = size_file.read()
    with open(working_dir +f"moldata-{file_name}-atomids.dat", "rb") as binary_file:
        atom_id = binary_file.read()
        atom_ids = struct.unpack("b" * len(atom_id), atom_id)
    with open(working_dir +f"moldata-{file_name}-energies.dat", "rb") as energy_file:
        energies = energy_file.read()
        energy = struct.unpack("f" * ((len(energies)) // 4), energies)
    coordinates = []
    with open(working_dir +f"moldata-{file_name}-coords.dat", "rb") as coordinates_file:
        while True:
            coord = coordinates_file.read(12) #reading 12 bytes at a time to extract the starting 3 coordinate of 1 atom
            if not coord: break
            coord = struct.unpack('f'*3, coord)
            coordinates.append(coord)
            
    return size, atom_ids, energy, coordinates
     

In [7]:
def get_atom_ids(mol_index,size, atom_ids):

   
    if mol_index == 1:
        return atom_ids[:size[1]]
    
    else:
        starting_element = 0
        ending_ele = 0
        for i in range(mol_index):
            starting_element +=size[i]

        ending_ele = size[mol_index]+starting_element

    return atom_ids[starting_element:ending_ele]    
  

In [16]:
size_1, atom_ids_1 ,energy_1 , coordinates_1 = read_files(r"C:\Users\Kamal Maurya\Downloads\Halion Take-Home Coding Assignment V2\\", 0)

In [11]:
def fif(mol_index):
    file_name = 0
    if mol_index <=65536:
        file_name = 0
    elif mol_index >= 65536 and mol_index <= 131072:
        file_name = 1
    else:
        file_name = 2
    
    return file_name

In [14]:
def read_molecule(working_dir: str, mol_index: int) -> tuple[float, np.ndarray, np.ndarray]:
    
    #getting the molecule size
    
    size, all_atom_ids, all_energies, coordinates = read_files(working_dir, mol_index)
    file_name = fif(mol_index)
    
    if file_name == 0 :
        mol_index = mol_index 
    elif file_name == 1:
        mol_index -= 65536
    else:
        mol_index -= 131072
        
    coords = np.array(get_coordinate_for_molecule(mol_index, size, coordinates))
    atom_ids = np.array(get_atom_ids(mol_index, size, all_atom_ids))
    energy = all_energies[mol_index]
    

    return (energy, coords, atom_ids)

In [15]:
molecule_1 = read_molecule(r"C:\Users\Kamal Maurya\Downloads\Halion Take-Home Coding Assignment V2\\", 196607)

In [ ]:
molecule_2 = read_molecule(r"C:\Users\Kamal Maurya\Downloads\Halion Take-Home Coding Assignment V2\\", 3)

In [18]:
size_1[0]

48

In [24]:
coordinates_1[48: 48+size_1[1]]

[(2.5634765625, 4.06494140625, 0.92529296875),
 (2.28271484375, 3.10791015625, -0.2294921875),
 (2.20458984375, 1.6552734375, 0.25390625),
 (1.9384765625, 0.6884765625, -0.908203125),
 (1.99951171875, -0.7373046875, -0.44921875),
 (3.23486328125, -1.435546875, -0.3515625),
 (4.541015625, -0.80322265625, -0.703125),
 (3.3056640625, -2.72216796875, 0.07568359375),
 (2.1142578125, -3.34228515625, 0.4248046875),
 (2.1826171875, -4.6435546875, 0.8740234375),
 (0.87158203125, -2.74169921875, 0.3564453125),
 (0.83984375, -1.4453125, -0.08056640625),
 (-0.46142578125, -0.79345703125, -0.16845703125),
 (-1.0400390625, -0.56396484375, 1.19873046875),
 (-2.32421875, 0.2685546875, 1.06689453125),
 (-3.32763671875, -0.44921875, 0.14404296875),
 (-4.5458984375, 0.380859375, -0.02685546875),
 (-4.6435546875, 1.67724609375, -0.57373046875),
 (-5.947265625, 2.05810546875, -0.54443359375),
 (-6.6845703125, 1.07177734375, -0.0048828125),
 (-5.869140625, 0.03173828125, 0.322265625),
 (-2.6904296875, -0.73

In [34]:
molecule_1[1]

array([[ 2.56347656e+00,  4.06494141e+00,  9.25292969e-01],
       [ 2.28271484e+00,  3.10791016e+00, -2.29492188e-01],
       [ 2.20458984e+00,  1.65527344e+00,  2.53906250e-01],
       [ 1.93847656e+00,  6.88476562e-01, -9.08203125e-01],
       [ 1.99951172e+00, -7.37304688e-01, -4.49218750e-01],
       [ 3.23486328e+00, -1.43554688e+00, -3.51562500e-01],
       [ 4.54101562e+00, -8.03222656e-01, -7.03125000e-01],
       [ 3.30566406e+00, -2.72216797e+00,  7.56835938e-02],
       [ 2.11425781e+00, -3.34228516e+00,  4.24804688e-01],
       [ 2.18261719e+00, -4.64355469e+00,  8.74023438e-01],
       [ 8.71582031e-01, -2.74169922e+00,  3.56445312e-01],
       [ 8.39843750e-01, -1.44531250e+00, -8.05664062e-02],
       [-4.61425781e-01, -7.93457031e-01, -1.68457031e-01],
       [-1.04003906e+00, -5.63964844e-01,  1.19873047e+00],
       [-2.32421875e+00,  2.68554688e-01,  1.06689453e+00],
       [-3.32763672e+00, -4.49218750e-01,  1.44042969e-01],
       [-4.54589844e+00,  3.80859375e-01

In [25]:
def uniform_random_rotation(x):
    def generate_random_z_axis_rotation():
        """Generate random rotation matrix about the z axis."""
        R = np.eye(3)
        x1 = np.random.rand()
        R[0, 0] = R[1, 1] = np.cos(2 * np.pi * x1)
        R[0, 1] = -np.sin(2 * np.pi * x1)
        R[1, 0] = np.sin(2 * np.pi * x1)
        return R
    # There are two random variables in [0, 1) here (naming is same as paper)
    x2 = 2 * np.pi * np.random.rand()
    x3 = np.random.rand()
    # Rotation of all points around x axis using matrix
    R = generate_random_z_axis_rotation()
    v = np.array([
        np.cos(x2) * np.sqrt(x3),
        np.sin(x2) * np.sqrt(x3),
        np.sqrt(1 - x3)
    ])
    H = np.eye(3) - (2 * np.outer(v, v))
    M = -(H @ R)
    x = x.reshape((-1, 3))
    mean_coord = np.mean(x, axis=0)
    return ((x - mean_coord) @ M) + mean_coord @ M

In [35]:
rotate = uniform_random_rotation(molecule_1[1])

In [29]:
molecule_1[1]

array([[ 2.56347656e+00,  4.06494141e+00,  9.25292969e-01],
       [ 2.28271484e+00,  3.10791016e+00, -2.29492188e-01],
       [ 2.20458984e+00,  1.65527344e+00,  2.53906250e-01],
       [ 1.93847656e+00,  6.88476562e-01, -9.08203125e-01],
       [ 1.99951172e+00, -7.37304688e-01, -4.49218750e-01],
       [ 3.23486328e+00, -1.43554688e+00, -3.51562500e-01],
       [ 4.54101562e+00, -8.03222656e-01, -7.03125000e-01],
       [ 3.30566406e+00, -2.72216797e+00,  7.56835938e-02],
       [ 2.11425781e+00, -3.34228516e+00,  4.24804688e-01],
       [ 2.18261719e+00, -4.64355469e+00,  8.74023438e-01],
       [ 8.71582031e-01, -2.74169922e+00,  3.56445312e-01],
       [ 8.39843750e-01, -1.44531250e+00, -8.05664062e-02],
       [-4.61425781e-01, -7.93457031e-01, -1.68457031e-01],
       [-1.04003906e+00, -5.63964844e-01,  1.19873047e+00],
       [-2.32421875e+00,  2.68554688e-01,  1.06689453e+00],
       [-3.32763672e+00, -4.49218750e-01,  1.44042969e-01],
       [-4.54589844e+00,  3.80859375e-01

In [36]:
rotate

array([[-1.06979759e+00, -2.32259839e+00, -4.17281651e+00],
       [ 7.06950002e-02, -1.52347097e+00, -3.54916859e+00],
       [-4.58434937e-01, -3.57100952e-01, -2.70683048e+00],
       [ 6.87092447e-01,  4.58443324e-01, -2.09147268e+00],
       [ 1.65929206e-01,  1.67318292e+00, -1.38433711e+00],
       [-1.13473833e-01,  2.87939093e+00, -2.08445750e+00],
       [ 9.82693009e-02,  3.01749840e+00, -3.55604005e+00],
       [-5.98676121e-01,  3.98209746e+00, -1.45870767e+00],
       [-8.21794829e-01,  3.89070620e+00, -9.20528467e-02],
       [-1.32907713e+00,  5.00267480e+00,  5.45099702e-01],
       [-5.74532532e-01,  2.76219438e+00,  6.66196448e-01],
       [-8.41151471e-02,  1.67143055e+00,  1.11738965e-03],
       [ 1.91915304e-01,  4.71517551e-01,  7.82115911e-01],
       [-1.08193974e+00, -1.48006496e-01,  1.28226082e+00],
       [-7.57055287e-01, -1.49090527e+00,  1.95357291e+00],
       [ 2.53373059e-01, -1.27985388e+00,  3.09733565e+00],
       [ 6.08668955e-01, -2.58406707e+00

In [33]:
molecule_1

(50.49803924560547,
 array([[ 2.56347656e+00,  4.06494141e+00,  9.25292969e-01],
        [ 2.28271484e+00,  3.10791016e+00, -2.29492188e-01],
        [ 2.20458984e+00,  1.65527344e+00,  2.53906250e-01],
        [ 1.93847656e+00,  6.88476562e-01, -9.08203125e-01],
        [ 1.99951172e+00, -7.37304688e-01, -4.49218750e-01],
        [ 3.23486328e+00, -1.43554688e+00, -3.51562500e-01],
        [ 4.54101562e+00, -8.03222656e-01, -7.03125000e-01],
        [ 3.30566406e+00, -2.72216797e+00,  7.56835938e-02],
        [ 2.11425781e+00, -3.34228516e+00,  4.24804688e-01],
        [ 2.18261719e+00, -4.64355469e+00,  8.74023438e-01],
        [ 8.71582031e-01, -2.74169922e+00,  3.56445312e-01],
        [ 8.39843750e-01, -1.44531250e+00, -8.05664062e-02],
        [-4.61425781e-01, -7.93457031e-01, -1.68457031e-01],
        [-1.04003906e+00, -5.63964844e-01,  1.19873047e+00],
        [-2.32421875e+00,  2.68554688e-01,  1.06689453e+00],
        [-3.32763672e+00, -4.49218750e-01,  1.44042969e-01],
    

In [30]:
def write_xyz(pos: np.ndarray, atom_ids: np.ndarray, file_location="test.xyz") -> str:
    """Given atomic coordinates, and element symbols, write a .xyz file which can be
    read by molecule visualization programs such as Avogadro. If your molecule looks
    like it makes sense, with bonds between the atoms, that's probably a good sign. If
    it looks like a mess, that's probably a bad sign."""

    els = get_el_sym(atom_ids)
    part1 = ""

    for adx, el in enumerate(els):
        x = pos[adx, 0]
        y = pos[adx, 1]
        z = pos[adx, 2]
        part1 += f"""\n{el:<3}{x:>15.5f}{y:>15.5f}{z:>15.5f}"""

    block = f"""{len(els)}\n{part1}\n"""
    with open(file_location, "w+") as out_file:
        out_file.write(block)

In [38]:
write_xyz(rotate, molecule_1[2] )

In [41]:
def total_num_molecules(working_dir):
    num_molecule = 0
    for i in range(3):
        with open(f"moldata-{i}-sizes.dat", "rb") as f:
            file = f.read()
            num_molecule+= len(file)
    return num_molecule

In [42]:
def tota_separation(coords_1,coords_2, atom_ids_1, atom_ids_2):
    leftmost_index = coords_1.argmax(axis = 0)[0]
    rightmost_index = coords_2.argmin(axis = 0)[0]
    
    leftmost_element = get_el_sym([atom_ids_1[leftmost_index]])
    rightmost_element = get_el_sym([atom_ids_2[rightmost_index]])
    
    van_der_waal = {'H' : 120 ,'B' : 192,'C' : 170, 'N' : 155, 'O' : 152, 'F' : 147, 'Na' : 227, 'Si' : 210, 'P': 180, 'S' : 180,
                    'Cl': 175, 'K': 275, 'Se': 190, 'Br': 185, 'I': 198}
    leftmost_element_dist = van_der_waal[leftmost_element[0]]
    rightmost_element_dist = van_der_waal[rightmost_element[0]]
    
    total_separation = coords_1[leftmost_index][0] + (leftmost_element_dist * 1e-12)+ (rightmost_element_dist * 1e-12) + abs(coords_2[rightmost_index][0])
    
    return total_separation
    

In [ ]:
coords_1, atom_ids_1 = molecule_1[1], molecule_1[2]

In [ ]:
coords_2, atom_ids_2 = molecule_2[1], molecule_2[2]

In [ ]:
get_van_der_dist(coords_1, coords_2, atom_ids_1, atom_ids_2)

In [ ]:
leftmost_index = coords_1.argmax(axis = 0)[0]
leftmost_element = get_el_sym([atom_ids_1[leftmost_index]])
leftmost_element[0]

In [ ]:
leftmost_element_dist = van_der_waal[leftmost_element[0]]
leftmost_element_dist

In [ ]:
H B C N O F Na Si P S Cl K Se Br I X

In [ ]:
van_der_waal = {'H' : 120 ,'B' : 192,'C' : 170, 'N' : 155, 'O' : 152, 'F' : 147, 'Na' : 227, 'Si' : 210, 'P': 180, 'S' : 180,
                    'Cl': 175, 'K': 275, 'Se': 190, 'Br': 185, 'I': 198}

In [ ]:
righmost_element

In [ ]:
196608/3

In [ ]:
molecule

In [ ]:
get_el_sym([0])

In [ ]:
fif(131073)

In [ ]:
65536 *2

In [17]:
df = pd.read_csv('data.csv')

In [18]:
df

Unnamed: 0  size                                              atoms  \
0                0    48  (2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 3, 2, 3, 2, 2, ...   
1                1    48  (2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 3, 2, 3, 2, 2, ...   
2                2    48  (2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 3, 2, 3, 2, 2, ...   
3                3    48  (2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 3, 2, 3, 2, 2, ...   
4                4    48  (2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 3, 2, 3, 2, 2, ...   
...            ...   ...                                                ...   
196603      196603    48  (2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 3, 2, 3, 2, 2, ...   
196604      196604    48  (2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 3, 2, 3, 2, 2, ...   
196605      196605    48  (2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 3, 2, 3, 2, 2, ...   
196606      196606    48  (2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 3, 2, 3, 2, 2, ...   
196607      196607    48  (2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 3, 2, 3, 2, 2, ...   

                                              coordinates   energies  
0       [(2.5634765625, 4.06494140625, 0.92529296875),...  50.498039  
1       [(2.5634765625, 4.06494140625, 0.92529296875),...  50.498039  
2       [(2.5634765625, 4.06494140625, 0.92529296875),...  50.498039  
3       [(2.5634765625, 4.06494140625, 0.92529296875),...  50.498039  
4       [(2.5634765625, 4.06494140625, 0.92529296875),...  50.498039  
...                                                   ...        ...  
196603  [(2.5634765625, 4.06494140625, 0.92529296875),...  50.498039  
196604  [(2.5634765625, 4.06494140625, 0.92529296875),...  50.498039  
196605  [(2.5634765625, 4.06494140625, 0.92529296875),...  50.498039  
196606  [(2.5634765625, 4.06494140625, 0.92529296875),...  50.498039  
196607  [(2.5634765625, 4.06494140625, 0.92529296875),...  50.498039  

[196608 rows x 5 columns]